# file: pip/tasks/installer.yml

- name: Create cache dir for pip downloads
  file:
    path: /var/cache/pip-installer
    mode: 0755
    state: directory

- name: Pip | Download the Pip installer to /var/cache/pip-installer
  get_url:
    url: "{{pip_install_url}}"
    dest: "/var/cache/pip-installer/get-pip.py"

- name: Pip | Run get-pip.py to intall Pip
  command: python /var/cache/pip-installer/get-pip.py
  register: pip_command
  changed_when: "'Requirement already up-to-date: pip' not in pip_command.stdout"
